# Generated by Django 5.0.6 on 2024-05-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clicker',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
