# Generated by Django 5.0.6 on 2024-05-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPapp', '0002_alter_clicker_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lesson',
            new_name='Lecture',
        ),
        migrations.RenameField(
            model_name='clicker',
            old_name='lesson',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='interview',
            old_name='lesson',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='lesson_name',
            new_name='lecture_name',
        ),
        migrations.RenameField(
            model_name='lessonstructure',
            old_name='lesson',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='lesson',
            new_name='lecture',
        ),
    ]
