# Generated by Django 5.0.6 on 2024-05-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FPapp', '0003_rename_lesson_lecture_rename_lesson_clicker_lecture_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonStructure',
            new_name='LectureStructure',
        ),
    ]
