# Generated by Django 5.0.6 on 2024-06-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FPapp', '0006_lecturestructure_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='start_date',
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
